import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Suspense } from "react";
import FacebookPixel from "@/components/FacebookPixel";
import WhatsAppButton from "@/components/WhatsAppButton";
import PromotionBanner from "@/components/PromotionBanner";
import GoogleTagManager from "@/components/GoogleTagManager";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={null}>
          <FacebookPixel />
          <GoogleTagManager gtmId="GTM-XXXXXXX" /> {/* REEMPLAZA CON TU ID */}
        </Suspense>
        <PromotionBanner />
        {children}
        <WhatsAppButton />
      </body>
    </html>
  );
}
